[build]
  command = "npm install && npm pack @prisma/client && tar -xzf prisma-client-*.tgz && cp -rf package/generator-build node_modules/@prisma/client/ && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
